version: "3"
services:
  nginx:
    build: ./nginx
    links: 
      - tile-interface:tile-interface
    ports: 
      - "8080:80"
  tile-interface:
    build: ./
    deploy:
      resources:
        limits:
          cpus: "1"
    ports:
      - "3000:3000"
    restart: on-failure
